### PR TITLE
Fixes setting committer author/email

### PR DESCRIPTION
**Pull request by npepinpe**
Overrides the committer author/email via environment variables instead of by using configuration options.

### CODE REVIEW

**Comment by npepinpe** [comment]
:crossed_fingers:

**Review by korthout — CHANGES_REQUESTED** [review]
This is a really nice solution! I was unaware that env vars could be used to override the values.

Please also update `test/setup.sh` to use this, for consistency.

**Comment by npepinpe** [comment]
I updated it, and now also enforce the environment variable instead of simply adding a default.

**Review by korthout — APPROVED** [review]
LGTM 🏆

**Pull request merged**
