### PR TITLE
Copy labels as specified by copy_labels_pattern

### PR DESCRIPTION
**Pull request by lheckemann**

### CODE REVIEW

**Comment by lheckemann** [comment]
CLA? Never mind.

**Comment by korthout** [comment]
Wow awesome work on this @lheckemann Too bad the CLA is a no go for you.

At the end of this month, I'll move this repo under my own account as part of the [v1 release](https://github.com/zeebe-io/backport-action/issues/289). The CLA will no longer be necessary from that moment onwards. Would you be willing to re-open the PR then?

**Comment by lheckemann** [comment]
I'd be glad to!

**Comment by korthout** [comment]
@lheckemann The CLA check should no longer pop up now. Please reopen the pull request when you have time.

**Comment by lheckemann** [comment]
#314

**Pull request closed without merging**
