### PR TITLE
feat: add relates to issue links

### LINKED ISSUE #3: Link backport PR to original issue
> Typically, when I backport a PR, I'll add a related to #123 (where 123 would be the original issue, not the PR being backported)

Original issue: https://github.com/zeebe-io/automation-lab/issues/43

### PR DESCRIPTION
**Pull request by korthout**
Uses the events of the pull request (a pull request is also an issue,
and thus has events), to determine which issues were linked to it at any
time. Since only the `connected` events are used, it can be the case
that an issue was unlinked or `unconnected` from the pull request.
Unlinked issues are not taken into account, so they will be used as if
they were still linked.

resolves #3

### CODE REVIEW

**Comment by domenkozar** [comment]
:pray:

**Comment by korthout** [comment]
I've been playing around with this version a bit, but it does not work. 😞 

The reason for this seems to be that the connected events are not fully supported for pull requests. 

I will close this PR and try an implementation using patterns to match issue references in the original PR's description. 

Specifically, I think `/#[0-9]+|(?:(?:https:\/\/)?(?:www\.)?github\.com\/.+\/issues\/[0-9]+)/gm` (see https://regex101.com/r/uDgGHZ/1) could be a good attempt to match any issue number references and urls to github issues.

**Comment by korthout** [comment]
> Only merged pull requests can be backported.

Example of https://github.com/zeebe-io/backport-action/issues/32

**Comment by korthout** [comment]
> Only merged pull requests can be backported.

This should no longer appear with #40

**Pull request closed without merging**
